### ISSUE TITLE
Traefik Config Snippets

### ISSUE THREAD

**Issue by purple4pur** [purple4pur/purple4pur.github.io#19]
> Apply to `traefik:v3.2`

### Example traefik `compose.yaml`

See [[TBD]](#) .

### Example `traefik.yaml`

```yaml
log:
  #level: "DEBUG"
api:
  dashboard: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedbydefault: false
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
certificatesResolvers:
  cloudflare:
    acme:
      email: "email@example.com"
      storage: "/letsencrypt/acme_cloudflare.json"
      dnsChallenge:
        provider: "cloudflare"
        resolvers:
          - "8.8.8.8:53"
          - "1.1.1.1:53"
  myresolver:
    acme:
      email: "email@example.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"
```

### Route a https URL to an internal service on :8080

```yaml
    ...
    labels:
      traefik.enable: true
      traefik.http.services.SERVICE_X.loadbalancer.server.port: "8080"
      traefik.http.routers.ROUTER_X.rule: "..."
      traefik.http.routers.ROUTER_X.entrypoints: "websecure"
      traefik.http.routers.ROUTER_X.tls.certresolver: "cloudflare"
      traefik.http.routers.ROUTER_X.service: "SERVICE_X"
```

### middleware: redirectregex

Redirect `dashboard.hostname.com` to `https://hostname.com/dashboard`:

```yaml
    ...
    labels:
      ...
      # define redirectregex
      traefik.http.middlewares.dashboard_redirect.redirectregex.regex: "^((?:https?:\\/\\/)?dashboard\\.hostname\\.com)"
      traefik.http.middlewares.dashboard_redirect.redirectregex.replacement: "https://hostname.com/dashboard"
      ...
      # use redirectregex
      traefik.http.routers.dashboard_redirect.middlewares: "dashboard_redirect"
      #                    ^-router name                    ^-middleware name
```

### middleware: basicAuth

```yaml
    ...
    labels:
      ...
      # define basicAuth
      traefik.http.middlewares.admin_auth.basicAuth.users: "test:$apr1$7ij1g6q3$WiPOcMX6m/gWCC3kKP9kh0"
      ...
      # use basicAuth
      traefik.http.routers.dashboard.middlewares: "admin_auth"
```

, where `users` field is Apache salted MD5 generated by `htpasswd`:

```sh
htpasswd -n USERNAME
```
